-- Procurement proposals generated by the proposal agent.

CREATE TABLE IF NOT EXISTS procurement_proposals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workflow_id UUID REFERENCES agent_workflows(id) ON DELETE CASCADE,
    company_id UUID NOT NULL,
    proposal_type TEXT DEFAULT 'standard',
    comparative_statement JSONB NOT NULL DEFAULT '{}',
    savings_summary JSONB NOT NULL DEFAULT '{}',
    recommendation TEXT,
    generated_by TEXT DEFAULT 'ai',
    approved_by UUID REFERENCES auth.users(id),
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_proposals_workflow ON procurement_proposals(workflow_id);
CREATE INDEX idx_proposals_company ON procurement_proposals(company_id);

ALTER TABLE procurement_proposals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access on proposals"
    ON procurement_proposals FOR ALL
    USING (auth.role() = 'service_role');
